# Generated by Django 2.2.4 on 2019-11-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='删除标记')),
                ('module', models.CharField(max_length=128, verbose_name='模块')),
                ('clazz', models.CharField(max_length=128, verbose_name='类名')),
                ('method', models.CharField(max_length=128, verbose_name='方法名')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'tb_test_case',
            },
        ),
        migrations.CreateModel(
            name='Testplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=128, verbose_name='测试任务名称')),
                ('module', models.CharField(max_length=128, verbose_name='模块')),
                ('remark', models.CharField(max_length=128, null=True, verbose_name='备注')),
                ('report', models.CharField(max_length=128, null=True, verbose_name='报告')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'db_table': 'test_plan',
            },
        ),
        migrations.CreateModel(
            name='Caseplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='删除标记')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='测试用例')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Testplan', verbose_name='测试任务')),
            ],
            options={
                'verbose_name': '测试任务用例',
                'verbose_name_plural': '测试任务用例',
                'db_table': 'tb_plan_case',
            },
        ),
    ]
